# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qCqgWiFCScOhzHHDs5GdGt1A_PeWy6Tz
"""

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from datasets import load_dataset
import numpy as np
from scipy.special import softmax

# Load the pre-trained emotion detection model and tokenizer
MODEL = "bhadresh-savani/distilbert-base-uncased-go-emotions"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

# Define emotion labels
emotion_labels = [
    "admiration", "amusement", "anger", "annoyance", "approval", "caring", "confusion", "curiosity",
    "desire", "disappointment", "disapproval", "disgust", "embarrassment", "excitement", "fear",
    "gratitude", "grief", "joy", "love", "nervousness", "optimism", "pride", "realization", "relief",
    "remorse", "sadness", "surprise", "neutral"
]

def predict_emotion(text):
    """Predicts the emotion of the given text."""
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    scores = outputs.logits.numpy()[0]
    scores = softmax(scores)
    emotion_scores = {emotion_labels[i]: float(scores[i]) for i in range(len(emotion_labels))}
    sorted_emotions = sorted(emotion_scores.items(), key=lambda x: x[1], reverse=True)
    dominant_emotion = sorted_emotions[0]
    return sorted_emotions, dominant_emotion

# Test the function with an example
text = "I am so happy and excited today!"
result, dominant = predict_emotion(text)
print("Emotion Predictions:")
for emotion, score in result[:5]:  # Display top 5 emotions
    print(f"{emotion}: {score:.4f}")
print(f"\nDominant Emotion: {dominant[0]} ({dominant[1]:.4f})")

import ipywidgets as widgets

from IPython.display import display

from transformers import pipeline



# Initialize the emotion detection pipeline

emotion_pipeline = pipeline("sentiment-analysis", model="j-hartmann/emotion-english-distilroberta-base")



# Function to detect emotion

def detect_emotion(text):

    result = emotion_pipeline(text)

    return result[0]['label']



# Create widgets

heading = widgets.HTML(value="<h1>Emotion Detection</h1>")

text_input = widgets.Text(placeholder='Enter your text here...')

button = widgets.Button(description='Detect Emotion')

output = widgets.Output()



# Define button click event

def on_button_click(b):

    with output:

        output.clear_output()

        text = text_input.value

        emotion = detect_emotion(text)

        print(f"The emotion of the text is: {emotion}")



button.on_click(on_button_click)



# Display widgets

display(heading, text_input, button, output)



import ipywidgets as widgets

from IPython.display import display

from transformers import pipeline



# Initialize the emotion detection pipeline

emotion_pipeline = pipeline("sentiment-analysis", model="j-hartmann/emotion-english-distilroberta-base")



# Function to detect emotion

def detect_emotion(text):

    result = emotion_pipeline(text)

    return result[0]['label']



# Create widgets

heading = widgets.HTML(value="<h1>Emotion Detection</h1>")

text_input = widgets.Text(placeholder='Enter your text here...')

button = widgets.Button(description='Detect Emotion')

output = widgets.Output()



# Define button click event

def on_button_click(b):

    with output:

        output.clear_output()

        text = text_input.value

        emotion = detect_emotion(text)

        print(f"The emotion of the text is: {emotion}")



button.on_click(on_button_click)



# Display widgets

display(heading, text_input, button, output)